name: Scambletron CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main

jobs:
  code-check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: pre-commit/action@v3.0.1

#   pytest:
#     if: github.event.pull_request.draft == false
#     strategy:
#         matrix:
#             os: [ubuntu-latest]
#             python-version: ["3.11", "3.12", "3.13"]
#     runs-on: ${{ matrix.os }}
#     steps:
#       - uses: actions/checkout@v4

#       - name: Install uv
#         uses: astral-sh/setup-uv@v3
#         with:
#           enable-cache: true

#       - name: Set up Python
#         run: uv python install ${{ matrix.python-version }}

#       - name: Install Dependencies
#         run: uv sync --extra test

#       - name: Log installed packages
#         run: uv pip list

#       - name: Test with pytest
#         run: uv run pytest
